"""
Django settings for Ecommerce project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url
import cloudinary  # for images on production

# Load variables from a local .env file (ignored in production, where
# real environment variables are set by the host, e.g. Render).
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Comma-separated list of allowed hostnames, configurable per
# environment via the ALLOWED_HOSTS env var (see render.yaml).
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',
    'core',
    'products',
    'accounts',
    'ckeditor',
    'cart.apps.CartConfig',
    'checkout',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves compressed static files efficiently without a separate
    # web server/CDN, works well on platforms like Render.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Makes `cart_item_count` available in every template
                # (powers the cart badge in the site header).
                'cart.context_processor.cart_item_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ecommerce.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Uses dj_database_url so the same setting works both locally (via a
# DATABASE_URL in .env) and on Render (which injects DATABASE_URL
# automatically from the managed Postgres instance, see render.yaml).
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', '')
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Compresses and hashes static file names for cache-busting, served
# via WhiteNoise without needing a separate static file host.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# User-uploaded product images (local/dev storage path).
MEDIA_URL = '/product_images/'
MEDIA_ROOT = BASE_DIR / 'product_media'

# Toggle between local media storage (dev) and Cloudinary (production),
# controlled via the USE_CLOUDINARY env var.
USE_CLOUDINARY = os.getenv("USE_CLOUDINARY") == "True"

if USE_CLOUDINARY:
  DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

  import cloudinary
  cloudinary.config(
    cloud_name = os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key = os.getenv("CLOUDINARY_API_KEY"),
    api_secret = os.getenv("CLOUDINARY_API_SECRET"),
  )

# Redirect target after a successful Django auth login (used by
# built-in auth views; our custom accounts views redirect explicitly
# instead, see accounts/views.py).
LOGIN_REDIRECT_URL = '/'

# Stripe API credentials, used by checkout/views.py for creating
# Checkout Sessions and verifying webhook signatures.
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')

# Required when the site is served behind a proxy/load balancer over
# HTTPS (e.g. Render) so Django's CSRF protection trusts the real origin.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
# Tells Django to trust the X-Forwarded-Proto header from the proxy so
# request.is_secure() works correctly behind Render's load balancer.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Cloudinary is configured unconditionally here as well (in addition
# to the USE_CLOUDINARY block above) so the SDK has valid credentials
# available even when only used ad-hoc (e.g. via the admin).
cloudinary.config(
    cloud_name = os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key = os.getenv("CLOUDINARY_API_KEY"),
    api_secret = os.getenv("CLOUDINARY_API_SECRET"),
)

# Outgoing email (account verification links) is sent via SendGrid's
# SMTP relay. See accounts/views.py -> UserRegister for usage.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'apikey'  # SendGrid convention: literal string "apikey", the real secret goes in the password.
EMAIL_HOST_PASSWORD = os.getenv('SENDGRID_API_KEY')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# Django's cryptographic signing key (sessions, password reset tokens,
# email verification tokens, etc.). Must be kept secret and unique per
# environment -- never commit a real value, always inject via env var.
SECRET_KEY = os.getenv('SECRET_KEY')
